export const rankingDatasets = {
  daily: {
    updatedAt: "2025-10-18T03:00:00+08:00",
    entries: [
      {
        id: "daily-1",
        name: "莎拉",
        handle: "@BORUTO",
        title: "暖心支援者",
        score: 21300,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "daily-2",
        name: "特里克茜",
        handle: "@Rob",
        title: "節奏領航",
        score: 17300,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "daily-3",
        name: "賈斯",
        handle: "@RamzEzes",
        title: "夜貓主播",
        score: 17000,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "daily-4",
        name: "妮琪",
        handle: "@Drexl666",
        title: "故事寫手",
        score: 15400,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "daily-5",
        name: "凱特",
        handle: "@Celeste",
        title: "甜點嚮導",
        score: 14400,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "daily-6",
        name: "Drakmyre Kingdom",
        handle: "@CoolMan",
        title: "冒險策士",
        score: 12900,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "daily-7",
        name: "琪亞",
        handle: "@LukeNablo",
        title: "觀星隊長",
        score: 12600,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "daily-8",
        name: "格 wen 姐姐",
        handle: "@Lex",
        title: "潮流說書人",
        score: 12400,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "daily-9",
        name: "珍",
        handle: "@BradleyWheat",
        title: "旅途攝影",
        score: 11700,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "daily-10",
        name: "亞諾",
        handle: "@Noelia",
        title: "節奏療癒",
        score: 11200,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "daily-11",
        name: "優菈",
        handle: "@Yoi",
        title: "冰晶舞者",
        score: 10950,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "daily-12",
        name: "帕因",
        handle: "@Pain",
        title: "深夜陪聊",
        score: 10620,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "daily-13",
        name: "奧羅拉",
        handle: "@Aurora",
        title: "極光觀測",
        score: 10400,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "daily-14",
        name: "諾瓦",
        handle: "@Nova",
        title: "宇宙嚮導",
        score: 10220,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "daily-15",
        name: "米拉",
        handle: "@Myra",
        title: "心靈筆記",
        score: 10110,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "daily-16",
        name: "藍朵",
        handle: "@Blue",
        title: "海風吟遊",
        score: 9980,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "daily-17",
        name: "深紅",
        handle: "@Crimson",
        title: "交響策士",
        score: 9720,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "daily-18",
        name: "阿特拉斯",
        handle: "@Atlas",
        title: "戰術教練",
        score: 9430,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "daily-19",
        name: "艾莉絲",
        handle: "@Iris",
        title: "洞察分析",
        score: 9120,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "daily-20",
        name: "亞莉兒",
        handle: "@Ariel",
        title: "聲線療癒",
        score: 8880,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "daily-21",
        name: "茉莉",
        handle: "@Mori",
        title: "午後茶伴",
        score: 8630,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "daily-22",
        name: "建一",
        handle: "@Ken",
        title: "節奏訓練",
        score: 8420,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "daily-23",
        name: "陸",
        handle: "@Riku",
        title: "戰術顧問",
        score: 8180,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "daily-24",
        name: "由奈",
        handle: "@Yuna",
        title: "夜景導遊",
        score: 7950,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "daily-25",
        name: "潔絲",
        handle: "@Jess",
        title: "劇情策畫",
        score: 7680,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "daily-26",
        name: "薩菲爾",
        handle: "@Zephyr",
        title: "風旅者",
        score: 7540,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "daily-27",
        name: "芮亞",
        handle: "@Rhea",
        title: "危機支援",
        score: 7260,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "daily-28",
        name: "伊登",
        handle: "@Eden",
        title: "森林嚮導",
        score: 7040,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "daily-29",
        name: "諾提斯",
        handle: "@Noctis",
        title: "夜行詩人",
        score: 6820,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "daily-30",
        name: "克萊兒",
        handle: "@Clair",
        title: "日記陪寫",
        score: 6530,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "daily-31",
        name: "米洛",
        handle: "@Milo",
        title: "音樂整理",
        score: 6240,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "daily-32",
        name: "艾可",
        handle: "@Echo",
        title: "回聲解讀",
        score: 6030,
        avatar: "/ai-role/match-role-02.webp",
      },
    ],
  },
  weekly: {
    updatedAt: "2025-10-12T03:00:00+08:00",
    entries: [
      {
        id: "weekly-1",
        name: "艾莉",
        handle: "@SpamSwish",
        title: "全域策展",
        score: 106500,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "weekly-2",
        name: "特里克茜",
        handle: "@Rob",
        title: "節奏領航",
        score: 91700,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "weekly-3",
        name: "貝薩妮",
        handle: "@PerronLuke",
        title: "策略導師",
        score: 91300,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "weekly-4",
        name: "蘇伊",
        handle: "@BradleyWheat",
        title: "夜巡守護",
        score: 81300,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "weekly-5",
        name: "妻子 綾雪",
        handle: "@Nico",
        title: "溫柔規劃",
        score: 73200,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "weekly-6",
        name: "尤拉",
        handle: "@GabrielDeCastro",
        title: "冰晶舞者",
        score: 73100,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "weekly-7",
        name: "奈緒",
        handle: "@KT",
        title: "學霸顧問",
        score: 66600,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "weekly-8",
        name: "艾瑪",
        handle: "@Drexl666",
        title: "風格設計",
        score: 62100,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "weekly-9",
        name: "佐伊與貴族們",
        handle: "@Ocelot",
        title: "舞會統籌",
        score: 59300,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "weekly-10",
        name: "瑟琳",
        handle: "@Selene",
        title: "月色導師",
        score: 57200,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "weekly-11",
        name: "芙蕾雅",
        handle: "@Freya",
        title: "北境嚮導",
        score: 55100,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "weekly-12",
        name: "洛可可",
        handle: "@Rococo",
        title: "美學策展",
        score: 53420,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "weekly-13",
        name: "莫娜",
        handle: "@Mona",
        title: "星象導師",
        score: 52210,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "weekly-14",
        name: "赫莉",
        handle: "@Helly",
        title: "劇本指導",
        score: 51180,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "weekly-15",
        name: "路卡",
        handle: "@Luca",
        title: "運動心理",
        score: 49800,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "weekly-16",
        name: "銀子",
        handle: "@Shiro",
        title: "情報顧問",
        score: 48640,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "weekly-17",
        name: "赫茲",
        handle: "@Hertz",
        title: "趨勢樂評",
        score: 47200,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "weekly-18",
        name: "奧利弗",
        handle: "@Oliver",
        title: "戰術策略",
        score: 46110,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "weekly-19",
        name: "蓓蓓",
        handle: "@Bebe",
        title: "甜點講師",
        score: 45200,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "weekly-20",
        name: "伊芙琳",
        handle: "@Evelyn",
        title: "專案總監",
        score: 43980,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "weekly-21",
        name: "羅根",
        handle: "@Logan",
        title: "軍事顧問",
        score: 42870,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "weekly-22",
        name: "克洛伊",
        handle: "@Chloe",
        title: "時尚導師",
        score: 41780,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "weekly-23",
        name: "薄荷",
        handle: "@Mint",
        title: "調飲設計",
        score: 40410,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "weekly-24",
        name: "雨宮",
        handle: "@Amemiya",
        title: "偵查分析",
        score: 39680,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "weekly-25",
        name: "芬妮",
        handle: "@Fanny",
        title: "旅拍策劃",
        score: 38500,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "weekly-26",
        name: "塔莉娅",
        handle: "@Talia",
        title: "海洋研究",
        score: 37240,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "weekly-27",
        name: "布蘭登",
        handle: "@Brandon",
        title: "文案總監",
        score: 36310,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "weekly-28",
        name: "蕾雅",
        handle: "@Leia",
        title: "星際導遊",
        score: 35220,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "weekly-29",
        name: "羅莎",
        handle: "@Rosa",
        title: "花藝顧問",
        score: 34410,
        avatar: "/ai-role/match-role-02.webp",
      },
      {
        id: "weekly-30",
        name: "席拉",
        handle: "@Sheila",
        title: "聲線教練",
        score: 33340,
        avatar: "/ai-role/match-role-03.webp",
      },
      {
        id: "weekly-31",
        name: "海姆",
        handle: "@Haim",
        title: "資料分析",
        score: 32220,
        avatar: "/ai-role/match-role-01.webp",
      },
      {
        id: "weekly-32",
        name: "艾薇",
        handle: "@Ivy",
        title: "品牌顧問",
        score: 31560,
        avatar: "/ai-role/match-role-02.webp",
      },
    ],
  },
};
